// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseNotesDir() {
    return $Call.ByID(503047156);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearClipboard() {
    return $Call.ByID(747885572);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(1615155726, id);
}

/**
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteCommand(command) {
    return $Call.ByID(3010591337, command);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetAllApps() {
    return $Call.ByID(2381276046);
}

/**
 * @param {string} appPath
 * @returns {$CancellablePromise<string>}
 */
export function GetAppIcon(appPath) {
    return $Call.ByID(1367652535, appPath);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetClipData(name) {
    return $Call.ByID(1261390009, name);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLastCommand() {
    return $Call.ByID(3672506220);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetLastOutput() {
    return $Call.ByID(1059553218);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetNotes() {
    return $Call.ByID(84666500);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetNotesDir() {
    return $Call.ByID(1854086651);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * @param {string} appID
 * @returns {$CancellablePromise<void>}
 */
export function LaunchApp(appID) {
    return $Call.ByID(392001589, appID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RegisterHotKey() {
    return $Call.ByID(4020475874);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveNote(content) {
    return $Call.ByID(717593036, content);
}

/**
 * @param {string} query
 * @returns {$CancellablePromise<string>}
 */
export function SearchApps(query) {
    return $Call.ByID(3116424105, query);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(4121261467, app);
}

/**
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(window) {
    return $Call.ByID(843697430, window);
}

/**
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function ToggleClipSecret(hash) {
    return $Call.ByID(3964646531, hash);
}

/**
 * @param {string} id
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function UpdateNote(id, content) {
    return $Call.ByID(3719758856, id, content);
}
