// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * @returns {$CancellablePromise<string>}
 */
export function ChooseNotesDir() {
    return $Call.ByID(503047156);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function ClearClipboard() {
    return $Call.ByID(747885572);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNote(id) {
    return $Call.ByID(1615155726, id);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetClipData(name) {
    return $Call.ByID(1261390009, name);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetNotes() {
    return $Call.ByID(84666500);
}

/**
 * @returns {$CancellablePromise<string>}
 */
export function GetNotesDir() {
    return $Call.ByID(1854086651);
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function Greet(name) {
    return $Call.ByID(2659711170, name);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Hide() {
    return $Call.ByID(3538035797);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RegisterHotKey() {
    return $Call.ByID(4020475874);
}

/**
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveNote(content) {
    return $Call.ByID(717593036, content);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApplication(app) {
    return $Call.ByID(4121261467, app);
}

/**
 * @param {application$0.WebviewWindow | null} window
 * @returns {$CancellablePromise<void>}
 */
export function SetMainWindow(window) {
    return $Call.ByID(843697430, window);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Show() {
    return $Call.ByID(2781088484);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Toggle() {
    return $Call.ByID(1190013837);
}

/**
 * @param {string} hash
 * @returns {$CancellablePromise<void>}
 */
export function ToggleClipSecret(hash) {
    return $Call.ByID(3964646531, hash);
}

/**
 * @param {string} id
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function UpdateNote(id, content) {
    return $Call.ByID(3719758856, id, content);
}
