// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetAllApps() {
  return window['go']['main']['App']['GetAllApps']();
}

export function GetClipData(arg1) {
  return window['go']['main']['App']['GetClipData'](arg1);
}

export function GetLastCommand() {
  return window['go']['main']['App']['GetLastCommand']();
}

export function GetLastOutput() {
  return window['go']['main']['App']['GetLastOutput']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function RegisterHotKey() {
  return window['go']['main']['App']['RegisterHotKey']();
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}
