// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseNotesDir() {
  return window['go']['main']['App']['ChooseNotesDir']();
}

export function ClearClipboard() {
  return window['go']['main']['App']['ClearClipboard']();
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetAllApps() {
  return window['go']['main']['App']['GetAllApps']();
}

export function GetAppIcon(arg1) {
  return window['go']['main']['App']['GetAppIcon'](arg1);
}

export function GetClipData(arg1) {
  return window['go']['main']['App']['GetClipData'](arg1);
}

export function GetLastCommand() {
  return window['go']['main']['App']['GetLastCommand']();
}

export function GetLastOutput() {
  return window['go']['main']['App']['GetLastOutput']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function GetNotesDir() {
  return window['go']['main']['App']['GetNotesDir']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LaunchApp(arg1) {
  return window['go']['main']['App']['LaunchApp'](arg1);
}

export function RegisterHotKey() {
  return window['go']['main']['App']['RegisterHotKey']();
}

export function SaveNote(arg1) {
  return window['go']['main']['App']['SaveNote'](arg1);
}

export function SearchApps(arg1) {
  return window['go']['main']['App']['SearchApps'](arg1);
}

export function ToggleClipSecret(arg1) {
  return window['go']['main']['App']['ToggleClipSecret'](arg1);
}

export function UpdateNote(arg1, arg2) {
  return window['go']['main']['App']['UpdateNote'](arg1, arg2);
}
