// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteCommand(arg1:string):Promise<string>;

export function GetAllApps():Promise<string>;

export function GetClipData(arg1:string):Promise<string>;

export function GetLastCommand():Promise<string>;

export function GetLastOutput():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LaunchApp(arg1:string):Promise<void>;

export function RegisterHotKey():Promise<void>;

export function SearchApps(arg1:string):Promise<string>;
